---
title: "Project Proposal"
output: html_document
date: "*November 18, 2020*"
---

## Group Name: A.K.A - R
## Group Members:
- [Aybike Dilek](https://pjournal.github.io/mef04-AybikeDilek/)
- [Kami Üçkardeş](https://pjournal.github.io/mef04-KamiUckardes/)
- [Alican Sevimay](https://pjournal.github.io/mef04-AlicanSevimay/)
- [Betül Parlar](https://pjournal.github.io/mef04-parlarbetul/)

## Project Proposal

The data shows the power production of Turkey. Real time generation data consist of 17 columns with 2 categorical and 15 numerical variables. It is datetime-based data and each column shows the amount of energy production in MWh’s, that is earned from these resources. The data contains information between 1st of May, 2013 and 20th of July, 2020, for 24 hours. The data is collected from Turkish Energy Exchange.

- *Date* (date,categorical) : Date interval of the dataset.
- *Hour* (int,categorical) : Hour interval of the dataset.
- *Natural Gas* (Float, continuous) : Energy gained from natural gas in MWh.
- *Dammed Hydro* (Float, continuous) : Energy gained from dams via hydro in MWh.
- *Lignite* (Float, continuous) : Energy gained from lignites in MWh.
- *River* (Float, continuous) : Energy gained from rivers in MWh.
- *Import Coal* (Float, continuous) : Energy gained from coals which are not produced inside of the country in MWh.
- *Wind* (Float, continuous) : Energy gained from winds in MWh.
- *Sun* (Float, continuous) : Energy gained from sun in MWh.
- *Fuel Oil* (Float, continuous) : Energy gained from fuel oil in MWh.
- *Geothermal* (Float, continuous) : Energy gained from geothermal activities in MWh.
- *Asphaltite Coal* (Float, continuous) : Energy gained from asphaltite coal in MWh.
- *Black Coal* (Float, continuous) : Energy gained from black coal in MWh.
- *Biomass* (Float, continuous) : Energy gained from biomass in MWh.
- *Naphtha* (Float, continuous) : Energy gained from naphtha in MWh.
- *LNG* (Float, continuous) : Energy gained from liquefied natural gas in MWh.
- *Import-export* (Float, continuous) : The balance of imported and exported energy in MWh.

## Learning Outcomes

At the end of the study the group –a-k-a-r expect to observe;

-	Turkey’s energy profile (renewable and nonrenewable energy production trends)
-	Whether there is a relationship in the type of energy generation method on an hourly, daily, monthly or quarterly basis.
-	Is there a relationship between the change in foreign currency and energy production method?
-	Is there a relationship between the change in foreign currency and export-import amounts (MWh)?
-	Whether the population growth has an effect on electricity generation, and if so, to determine whether it is equally divided among all production methods or one method is used more dominantly.

## Plan

- Creating a project roadmap to get a clear overview of the objectives.
- Adding external data sources like foreign currency and population.
- Data Wrangling as preprocessing section.
- Checking outliers and summarising data to deciding which central tendency method will be used for analysis.
- Exploratory Data Analysis with R packages such as "dplyr" and "lubridate".
- Visualizing data with R packages such as "ggplot2".
- Preparing a final Html report.
- Final project presentation.








